In [1]:
from datasets import load_dataset
import pandas as pd

C:\Users\rakes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from datasets import load_dataset
df = load_dataset("Rakesh7n/ncrt_eval_outputs", split="train").to_pandas()
print(len(df), df.duplicated(subset=["formatted_prompt", "adapter_output"]).sum())

Using the latest cached version of the dataset since Rakesh7n/ncrt_eval_outputs couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at C:\Users\rakes\.cache\huggingface\datasets\Rakesh7n___ncrt_eval_outputs\default\0.0.0\a56885b0377fa3ee9145d0b892d8d375ec4f86a2 (last modified on Sun Oct 11 12:50:40 2026).

524 11

In [4]:
df.duplicated(subset=["formatted_prompt", "adapter_output"]).sum()

np.int64(11)

In [5]:
df

,Explanation,Question,Answer,messages,formatted_prompt,base_output,adapter_output
0,In semiconductors like Silicon (Si) or Germani...,Provide an example of a semiconductor material...,An example of a semiconductor material where t...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user is asking for an example of a s...",The concept of holes is applicable to all semi...
1,Electric current is the flow of electric charg...,What is the formula for electric current?,The formula for electric current is \( I = \fr...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user is asking for the formula for e...",Electric current is the flow of electric charg...
2,Electromagnetism is the branch of physics that...,Describe the process of how a changing electri...,"When an electric field changes, it creates a t...","[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user wants me to describe how a chan...",Electromagnetic waves are a result of the inte...
3,The photoelectric effect is a phenomenon where...,What is the relationship between the energy of...,The energy of a photon (E) is directly proport...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user is asking about the relationshi...",The energy of a photon is directly proportiona...
4,Electromagnetic waves are formed by the oscill...,Describe the process by which electromagnetic ...,Electromagnetic waves propagate through space ...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user wants me to describe how electr...",Electromagnetic waves are a form of energy tha...
...,...,...,...,...,...,...,...
519,Bohr's model of the hydrogen atom is a fundame...,Provide an example of how Bohr's second postul...,Bohr's second postulate states that the angula...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user wants an example of how Bohr's ...","The Bohr model of the hydrogen atom, proposed ..."
520,Resonance in an RLC circuit occurs when the in...,What is the condition for resonance in an RLC ...,The condition for resonance in an RLC circuit ...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user is asking about the condition f...",Resonance in an RLC circuit occurs when the in...
521,Electrostatics is the study of electrical char...,Explain why a charged object loses its charge ...,A charged object loses its charge when touched...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user wants to know why a charged obj...","The question is: ""Explain why a charged object..."
522,Electric current is the flow of electric charg...,Describe what happens to the electrons in a co...,"When an electric field is applied, it exerts a...","[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user wants me to describe what happe...",Electrons are negatively charged particles tha...
523,Coulomb's Law describes the electrostatic forc...,Calculate the electric force between an electr...,"Using Coulomb's Law, F = k * (q_electron * q_p...","[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user wants me to calculate the elect...",The electric force between two charges is give...

In [7]:
df=df.drop_duplicates(subset=["formatted_prompt", "adapter_output"])
df

,Explanation,Question,Answer,messages,formatted_prompt,base_output,adapter_output
0,In semiconductors like Silicon (Si) or Germani...,Provide an example of a semiconductor material...,An example of a semiconductor material where t...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user is asking for an example of a s...",The concept of holes is applicable to all semi...
1,Electric current is the flow of electric charg...,What is the formula for electric current?,The formula for electric current is \( I = \fr...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user is asking for the formula for e...",Electric current is the flow of electric charg...
2,Electromagnetism is the branch of physics that...,Describe the process of how a changing electri...,"When an electric field changes, it creates a t...","[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user wants me to describe how a chan...",Electromagnetic waves are a result of the inte...
3,The photoelectric effect is a phenomenon where...,What is the relationship between the energy of...,The energy of a photon (E) is directly proport...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user is asking about the relationshi...",The energy of a photon is directly proportiona...
4,Electromagnetic waves are formed by the oscill...,Describe the process by which electromagnetic ...,Electromagnetic waves propagate through space ...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user wants me to describe how electr...",Electromagnetic waves are a form of energy tha...
...,...,...,...,...,...,...,...
519,Bohr's model of the hydrogen atom is a fundame...,Provide an example of how Bohr's second postul...,Bohr's second postulate states that the angula...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user wants an example of how Bohr's ...","The Bohr model of the hydrogen atom, proposed ..."
520,Resonance in an RLC circuit occurs when the in...,What is the condition for resonance in an RLC ...,The condition for resonance in an RLC circuit ...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user is asking about the condition f...",Resonance in an RLC circuit occurs when the in...
521,Electrostatics is the study of electrical char...,Explain why a charged object loses its charge ...,A charged object loses its charge when touched...,"[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user wants to know why a charged obj...","The question is: ""Explain why a charged object..."
522,Electric current is the flow of electric charg...,Describe what happens to the electrons in a co...,"When an electric field is applied, it exerts a...","[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user wants me to describe what happe...",Electrons are negatively charged particles tha...
523,Coulomb's Law describes the electrostatic forc...,Calculate the electric force between an electr...,"Using Coulomb's Law, F = k * (q_electron * q_p...","[{'role': 'system', 'content': ""Follow these s...",<|im_start|>system\nFollow these steps to answ...,"Okay, the user wants me to calculate the elect...",The electric force between two charges is give...

In [ ]:
ds=load_dataset("Rakesh7n/ncrt_eval_outputs")

C:\Users\rakes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\rakes\.cache\huggingface\hub\datasets--Rakesh7n--ncrt_eval_outputs. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Generating train split: 100%|██████████| 513/513 [00:00<00:00, 6956.09 examples/s]

:

In [3]:
ds['train']

Dataset({
    features: ['Explanation', 'Question', 'Answer', 'messages', 'formatted_prompt', 'base_output', 'adapter_output'],
    num_rows: 524
})

In [4]:
def reference_com(example):
    ans = example['Answer']
    exp = example['Explanation']
    return {"reference": f"Answer: {ans}\nExplanation: {exp}"}

In [5]:
ds=ds.map(reference_com)
ds=ds.remove_columns(['Explanation','Question','Answer','messages'])

In [6]:
ds['train'][0]

{'formatted_prompt': "<|im_start|>system\nFollow these steps to answer the user's question:\n1. First, reason step-by-step inside <think> tags. This is your internal monologue.\n2. After the </think> tag, provide a complete, helpful, and polished answer for the user that includes both a direct answer and an explanation.<|im_end|>\n<|im_start|>user\nProvide an example of a semiconductor material where the concept of holes is applicable.<|im_end|>\n<|im_start|>assistant\n<think>\n",
 'base_output': 'Okay, the user is asking for an example of a semiconductor material where the concept of holes is applicable. Let me start by recalling what holes mean in semiconductors. Holes are a key concept in semiconductor physics, especially in p-type materials. They represent the absence of an electron in the valence band, acting as positive charge carriers.\n\nFirst, I need to pick a material where holes are a significant part of conduction. Common semiconductors include silicon, germanium, gallium arsenide, etc. Silicon is the most widely used semiconductor in electronics, so it\'s a solid choice. But I should check if the user might be thinking of intrinsic or extrinsic semiconductors. Holes are crucial in p-type semiconductors, so materials like silicon doped with acceptors (like boron) would have holes as majority carriers.\n\nWait, the question says "the concept of holes is applicable." So even in intrinsic semiconductors, holes exist as minority carriers, but the concept is more prominent in p-type materials. The user might be a student learning semiconductor physics, so providing a clear example with context would help.\n\nI remember that in silicon, when doped with boron (a group 13 element), it becomes p-type. In this case, holes are the majority carriers. That\'s a classic example. The user might not know about doping, so I should explain that holes are created by doping. \n\nAlso, the user might confuse holes with actual holes (like in materials science), but in semiconductors, it\'s the charge carriers. I should clarify that holes are not physical particles but a quasiparticle concept. \n\nLet me think of other materials. Germanium is another common one, but silicon is more prevalent in modern tech. Gallium arsenide is used in high-speed devices, but silicon is more straightforward. \n\nThe answer should specify that silicon is the material, and in p-type silicon (doped with acceptors), holes are the majority carriers. That\'s a solid example. I should mention why it\'s applicable—because in p-type semiconductors, holes contribute significantly to electrical conduction. \n\nAlso, the user might need to know that holes are essential for understanding devices like diodes and transistors. Including that context could add value. \n\nWait, the question says "the concept of holes is applicable." So even in intrinsic silicon, holes exist, but the concept is most practically applied in p-type materials. To be precise',
 'adapter_output': 'The concept of holes is applicable to all semiconductors, but it is most commonly associated with p-type semiconductors. In p-type semiconductors, the majority carriers are holes, which are the absence of electrons in the valence band. This is a fundamental concept in semiconductor physics.\n</think>\n\nAnswer: The concept of holes is applicable to all semiconductors, but it is most commonly associated with p-type semiconductors. In p-type semiconductors, the majority carriers are holes, which are the absence of electrons in the valence band. This is a fundamental concept in semiconductor physics.',
 'reference': 'Answer: An example of a semiconductor material where the concept of holes is applicable is p-type silicon, which is doped with a trivalent impurity such as boron. The boron atoms create holes in the silicon lattice, enhancing its conductivity.\nExplanation: In semiconductors like Silicon (Si) or Germanium (Ge), each atom typically forms four covalent bonds with its neighboring atoms. However, if an atom has only three electrons to share (making it trivalent), it can only form three covalent bonds. The fourth bond will have a vacancy or "hole." This hole can move through the lattice as electrons from neighboring atoms jump to fill the hole, creating a new hole at the electron\'s original location. This process is fundamental to the conductivity of p-type semiconductors.'}

In [54]:
!pip uninstall langchain-google-vertexai

^C

In [7]:
ds1=ds['train'][0]
ds1['reference']

'Answer: An example of a semiconductor material where the concept of holes is applicable is p-type silicon, which is doped with a trivalent impurity such as boron. The boron atoms create holes in the silicon lattice, enhancing its conductivity.\nExplanation: In semiconductors like Silicon (Si) or Germanium (Ge), each atom typically forms four covalent bonds with its neighboring atoms. However, if an atom has only three electrons to share (making it trivalent), it can only form three covalent bonds. The fourth bond will have a vacancy or "hole." This hole can move through the lattice as electrons from neighboring atoms jump to fill the hole, creating a new hole at the electron\'s original location. This process is fundamental to the conductivity of p-type semiconductors.'

In [ ]:

# from langchain_huggingface import ChatHuggingFace
# from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
from datasets import Dataset
from ragas import evaluate
from ragas.metrics.collections import AnswerRelevancy, FactualCorrectness
from ragas.llms import LangchainLLMWrapper
from langchain_openai import ChatOpenAI

:

In [ ]:
judge_model = AutoModelForCausalLM.from_pretrained(
    "openbmb/MiniCPM5-1B",
    torch_dtype=torch.float16,
    device_map="auto"
)
judge_tokenizer = AutoTokenizer.from_pretrained("openbmb/MiniCPM5-1B")
judge_llm = ChatHuggingFace(
    llm=judge_model,
    tokenizer=judge_tokenizer
)
ragas_llm = LangchainLLMWrapper(judge_llm)

In [ ]:

judge = LangchainLLMWrapper(ChatOpenAI(model="gpt-4o-mini", temperature=0))

# Build the eval dataset
eval_ds = Dataset.from_dict({
    "question": ds1["formatted_prompt"],
    "answer": ds1["adapter_output"],   
    "ground_truth": ds["reference"],
})

result = evaluate(
    eval_ds,
    metrics=[
        answer_relevancy(llm=judge),
        factual_correctness(llm=judge),
    ],
)

print(result)

In [ ]:
import os
import json
from datasets import load_dataset, Dataset
from src.NcrtPhysicsQwen3.logger import logger
from src.NcrtPhysicsQwen3.config.configuration import ModelEvaluationConfig

from ragas import evaluate
from ragas.metrics import FactualCorrectness
# from ragas.metrics.collections import  FactualCorrectness
# from ragas.llms import LangchainLLMWrapper
# from langchain_openai import ChatOpenAI

import wandb
from dotenv import load_dotenv
load_dotenv()

from ragas.llms import llm_factory
from openai import AsyncOpenAI 




class DatasetPrep:
    def __init__(self):
        self.dataset_path = "Rakesh7n/ncrt_eval_outputs"

    def combine_cols(self, example):
        ans = example['Answer']
        exp = example['Explanation']
        return {"reference": f"Answer: {ans}\nExplanation: {exp}"}

    def load_test_data(self):
        ds = load_dataset(str(self.dataset_path), split="train")
        ds = ds.map(self.combine_cols)
        ds = ds.remove_columns(['Explanation', 'Question', 'Answer', 'messages'])
        ds=ds.select(range(1))
        eval_ds =Dataset.from_dict({
                "user_input": ds["formatted_prompt"],   # maps to user_input
                "response": ds["adapter_output"],        # maps to response
                "reference": ds["reference"],            # maps to reference
            })
        return ds

        


class ModelEvaluation:

    def __init__(self, config: ModelEvaluationConfig):
        self.config = config
        nim_client = AsyncOpenAI (
                base_url="https://integrate.api.nvidia.com/v1",
                api_key=os.getenv("NVIDIA_API_KEY"),
            )
        self.llm = llm_factory("meta/muse-glimmer-30b", client=nim_client)   
        self.ds = DatasetPrep().load_test_data()

    def run_evaluation(self, output_col="adapter_output"):

        metrics = [FactualCorrectness(llm=self.llm)]
        result = evaluate(
            dataset=self.ds,
            metrics=metrics,
            llm=self.llm,
            column_map={
                "user_input": "formatted_prompt",
                "response": "adapter_output",
                "reference": "reference",
            },
        )

        df = result.to_pandas()

        # --- Save JSON ---
        json_results = df.to_dict(orient="records")
        output_path = os.path.join(self.config.root_dir, "ragas_results.json")
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(json_results, f, indent=2, ensure_ascii=False)
        logger.info(f"Results saved to {output_path}")

        # --- Summary ---
        col = "factual_correctness"
        avg = float(df[col].mean())
        pass_rate = float((df[col] >= 0.5).mean())
        logger.info(f"Factual Correctness: avg={avg:.3f}, pass_rate={pass_rate:.1%}")

        # --- Wandb ---
        wandb.init(project="ncrt-physics-eval", name=f"ragas-{output_col}")
        wandb.log({"factual_correctness_avg": avg, "factual_correctness_pass_rate": pass_rate})

        table = wandb.Table(
            data=df[["question", "answer", "ground_truth", col]].values.tolist(),
            columns=["question", "answer", "ground_truth", "factual_correctness"],
        )
        wandb.log({"sample_table": table})
        wandb.finish()   

# --- Run ---
# config = ModelEvaluationConfig(root_dir="./")
# evaluator = ModelEvaluation(config)
# evaluator.run_evaluation()   

# import os
# import json
# from datasets import load_dataset
# from deepeval import evaluate
# from deepeval.test_case import LLMTestCase,  LLMTestCaseParams
# from deepeval.metrics import AnswerRelevancyMetric, GEval
# from deepeval.models import LocalModel
# from src.NcrtPhysicsQwen3.logger import logger
# from src.NcrtPhysicsQwen3.config.configuration import ModelEvaluationConfig
# import wandb
# from dotenv import load_dotenv
# load_dotenv()

# # class NIMModel(LocalModel):
# #     def __init__(self, model_name="meta/muse-glimmer-30b", temperature=0):
# #         self.model_name = model_name
# #         self.temperature = temperature
# #         from openai import OpenAI, AsyncOpenAI
# #         self.model = OpenAI(
# #             base_url=os.environ["LOCAL_MODEL_BASE_URL"],
# #             api_key=os.environ["NVIDIA_API_KEY"],
# #             timeout=120,
# #             max_retries=5,
# #         )
# #         self.async_model = AsyncOpenAI(
# #             base_url=os.environ["LOCAL_MODEL_BASE_URL"],
# #             api_key=os.environ["NVIDIA_API_KEY"],
# #             timeout=120,
# #             max_retries=5,
# #         )

# #     def generate(self, prompt: str) -> str:
# #         res = self.model.chat.completions.create(
# #             model=self.model_name,
# #             messages=[{"role": "user", "content": prompt}],
# #             temperature=self.temperature,
# #             max_tokens=512,
# #         )
# #         return res.choices[0].message.content

# #     async def a_generate(self, prompt: str) -> str:
# #         res = await self.async_model.chat.completions.create(  # ← async client
# #             model=self.model_name,
# #             messages=[{"role": "user", "content": prompt}],
# #             temperature=self.temperature,
# #             max_tokens=512,
# #         )
# #         return res.choices[0].message.content

# #     def get_model_name(self):
# #         return self.model_name   




# class DatasetPrep:
#     def __init__(self):
#         self.dataset_path = "Rakesh7n/ncrt_eval_outputs"

#     def combine_cols(self,example):

#         ans = example['Answer']
#         exp = example['Explanation']
#         return {"reference": f"Answer: {ans}\nExplanation: {exp}"}   

#     def load_test_data(self):            
#         ds = load_dataset(str(self.dataset_path), split="train") 
#         ds=ds.map(self.combine_cols)
#         ds=ds.select(range(1))
#         ds=ds.remove_columns(['Explanation','Question','Answer','messages'])
#         return ds

# from pydantic import BaseModel

# class ModelEvaluation:

#     def __init__(self, config: ModelEvaluationConfig):
#         self.config = config
#         self.llm = LocalModel(
#            LLMConfig("meta/muse-glimmer-30b",
#             0.0,)
#         )
#         # self.llm = NIMModel("meta/muse-glimmer-30b")
#         self.ds=DatasetPrep().load_test_data()

#     def metrics(self):
#         correctness_metric = GEval(
#         name="Correctness",
#         model=self.llm,
#         evaluation_steps=[
#             "Check whether the facts in 'actual output' contradict any facts in 'expected output'",
#             "Heavily penalize omission of key details from 'expected output'",
#             "Vague language or contradicting opinions are OK, but factual errors are not"
#         ],
#         evaluation_params=[ LLMTestCaseParams.ACTUAL_OUTPUT,  LLMTestCaseParams.EXPECTED_OUTPUT],
#         threshold=0.5,
#         )
#         relevancy_metric = AnswerRelevancyMetric(
#                 model=self.llm,
#                 threshold=0.5,
#             )
#         return correctness_metric, relevancy_metric
    
#     def build_test_cases(self,output_col):
#         test_cases = []
#         for i in range(len(self.ds)):
#             test_cases.append(LLMTestCase(
#                 input=self.ds["formatted_prompt"][i],
#                 actual_output=self.ds[output_col][i],
#                 expected_output=self.ds["reference"][i],
#             ))
#         return test_cases



#     def run_evaluation(self):
#         wandb.init(project="qwe3_4b_adapter-eval", name="adapter_evaluation_run")
#         correctness, relevancy = self.metrics()
#         test_cases = self.build_test_cases("adapter_output")
#         logger.info(f"Evaluating adapter on {len(test_cases)} samples...")
#         results = evaluate(test_cases=test_cases, metrics=[correctness, relevancy])

#         scores = {}
#         json_results = []

#         for i, tc_result in enumerate(results):
#             sample_entry = {
#                 "sample_id": i,
#                 "input": tc_result.test_case.input,
#                 "actual_output": tc_result.test_case.actual_output,
#                 "expected_output": tc_result.test_case.expected_output,
#                 "metrics": {},
#             }
#             for m in tc_result.metrics_data:
#                 scores.setdefault(m.name, []).append(m.score)
#                 sample_entry["metrics"][m.name] = m.score
#             json_results.append(sample_entry)

#         # Log averages to wandb (not per-sample in a loop)
#         for name, vals in scores.items():
#             avg = sum(vals) / len(vals)
#             pass_rate = sum(1 for v in vals if v >= 0.5) / len(vals)
#             logger.info(f"{name}: avg={avg:.3f}, pass_rate={pass_rate:.1%}")
#             wandb.log({f"{name}_avg": avg, f"{name}_pass_rate": pass_rate})

#         # Log per-sample table to wandb (one call, not 500)
#         import wandb as _wandb
#         table_data = [[e["sample_id"], e["input"][:100], e["metrics"].get("Correctness", 0), e["metrics"].get("Answer Relevancy", 0)] for e in json_results]
#         table = _wandb.Table(data=table_data, columns=["id", "input", "correctness", "relevancy"])
#         wandb.log({"sample_table": table})

#         output_path = os.path.join(self.config.root_dir, "evaluation_results.json")
#         with open(output_path, "w", encoding="utf-8") as f:
#             json.dump(json_results, f, indent=2, ensure_ascii=False)

#         logger.info(f"Results saved to {output_path}")
#         wandb.finish()   



#     # def run_evaluation(self):
#     #     wandb.init(
#     #         project="adapter-eval",
#     #         name="adapter_evaluation_run"
#     #     )
#     #     # self.load_test_data()
#     #     correctness, relevancy = self.metrics()
#     #     test_cases = self.build_test_cases("adapter_output")
#     #     logger.info(f"Evaluating adapter on {len(test_cases)} samples...")
#     #     results = evaluate(
#     #         test_cases=test_cases,
#     #         metrics=[correctness, relevancy],
#     #         # print_results=True,
#     #     )
#     #     # Extract scores
#     #     scores = {}
#     #     json_results = [] 
#     #     for tc_result in results:
#     #         sample_entry = {
#     #             "sample_id": tc_result.test_case_id,
#     #             "input": tc_result.test_case.input,
#     #             "actual_output": tc_result.test_case.actual_output,
#     #             "expected_output": tc_result.test_case.expected_output,
#     #             "metrics": {}
#     #         }
#     #         for m in tc_result.metrics_data:
#     #             scores.setdefault(m.name, []).append(m.score)
#     #             sample_entry["metrics"][m.name] = m.score
#     #             wandb.log({
#     #                 "sample_id": tc_result.test_case_id,
#     #                 f"{m.name}_score": m.score
#     #             })
#     #         json_results.append(sample_entry)
#     #     logger.info("=== Adapter Results ===")

#     #     for name, vals in scores.items():
#     #         avg = sum(vals) / len(vals)
#     #         pass_rate = sum(1 for v in vals if v >= 0.5) / len(vals)
#     #         logger.info(f"{name}: avg={avg:.3f}, pass_rate={pass_rate:.1%}")   
#     #         wandb.log({
#     #             f"{name}_avg": avg,
#     #             f"{name}_pass_rate": pass_rate
#     #         })

#     #     output_path = os.path.join(self.config.root_dir, "evaluation_results.json")
#     #     with open(output_path, "w", encoding="utf-8") as f:
#     #         json.dump(json_results, f, indent=2, ensure_ascii=False)

#     #     logger.info(f"Results saved to {output_path}")
#     #     wandb.finish()
# # --- Setup ---
# # os.environ["OPENAI_API_KEY"] = "your-api-key"  # or use `deepeval login`
# # base_cases = build_test_cases("base_output")
# # adapter_cases = build_test_cases("adapter_output")

# # import os
# # import torch
# # import wandb
# # from src.NcrtPhysicsQwen3.logger import logger
# # from src.NcrtPhysicsQwen3.config.configuration import ModelEvaluationConfig
# # from transformers import AutoTokenizer, AutoModelForCausalLM
# # from peft import PeftModel
# # from datasets import load_from_disk, Dataset
# # import tqdm
# # import json
# # import numpy as np



# # class ModelEvaluation:
# #     def __init__(self, config: ModelEvaluationConfig):
# #         self.config = config
# #         self.tokenizer = AutoTokenizer.from_pretrained(config.base_model_path)
# #         self.tokenizer.pad_token = self.tokenizer.eos_token


# # #     def generate_response(self,model,prompt,):
    
# # #     def evaluate(self):        
# # #         ds=load_from_disk(self.config.data_path)
# # #         base_model = AutoModelForCausalLM.from_pretrained(self.config.base_model_path)
# # #         # tokenizer= AutoTokenizer.from_pretrained(self.config.base_model_path)
# # #         adapter = PeftModel.from_pretrained(base_model, self.config.adapter_path)
# # #         return